### SPAM Detection - The Naive Bayes Algorithm in Python with Scikit-Learn 
D. Shahrokhian
https://stackabuse.com/the-naive-bayes-algorithm-in-python-with-scikit-learn/

In [9]:
import pandas as pd
import numpy as np


biggie_df = pd.read_csv('data//biggie_lyrics.csv', usecols=[1], encoding='latin-1', header=None)
biggie_df.columns = ["lyrics"]
biggie_df["lyrics"] = biggie_df["lyrics"].str.replace('[^\w\s]','')
biggie_df["lyrics"] = biggie_df["lyrics"].str.lower()

biggie_df.tail()

                                               lyrics
11  relax and take notes while i take tokes of the...
12  good evenin ladies and gentlemen\nhows everybo...
13  who shot ya\nseperate the weak from the obsole...
14  when i die fuck it i wanna go to hell\ncause i...
15  when the lala hits ya lyrics just splits ya\nh...

In [7]:
pac_df = pd.read_csv('data/2pac_lyrics.csv', usecols=[1], encoding='latin-1', header=None)
pac_df.columns = ["lyrics"]
pac_df["lyrics"] = pac_df["lyrics"].str.replace('[^\w\s]','')
pac_df["lyrics"] = pac_df["lyrics"].str.lower()

pac_df.tail()

                                               lyrics
11  i aint got no motherfucking friends\nthats why...
12  troublesome nigga\nhahaha troublesome 19mother...
13  change shit\ni guess change is good for any of...
14  i see no changes wake up in the morning and i ...
15  out on bail fresh out of jail california dream...

In [28]:
biggie_lyrics = biggie_df["lyrics"].values
biggie_lyrics = [ song.split('\n') for song in biggie_lyrics]
biggie_lyrics = [line for song in biggie_lyrics for line in song]
pac_lyrics = pac_df["lyrics"].values
pac_lyrics = [ song.split('\n') for song in pac_lyrics]
pac_lyrics = [line for song in pac_lyrics for line in song]

rap_lines = [] 

for line in biggie_lyrics:
    if len(line.split()) > 3:
        rap_lines.append(np.array([0,str(line)]))
        
for line in pac_lyrics:
    if len(line.split()) > 3:
        rap_lines.append(np.array([1,str(line)]))
        
rap_lines = np.array(rap_lines)
df = pd.DataFrame(rap_lines)
df.columns = ['label', 'lyrics']
df.head()
df.tail()

     label                                             lyrics
1965     1        so you know the row wont bow down to no man
1966     1  say what you say but give me that bomb beat fr...
1967     1                  let me serenade the streets of la
1968     1  from oakland to sactown the bay area and back ...
1969     1             cali is where they put their mack down

In [30]:
#df['label'] = df.label.map({'biggie': 0, '2pac': 1})
df['lyrics'] = df.lyrics.map(lambda x: x.lower())
df['lyrics'] = df.lyrics.str.replace('[^\w\s]', '')
df.head()

  label                                             lyrics
0     0                                  fuck all you hoes
1     0                            get a grip motherfucker
2     0  yeah this album is dedicated to all the teache...
3     0  id never amount to nothin to all the people th...
4     0  buildings that i was hustlin in front of that ...

In [31]:
# https://www.nltk.org/ Natural Language Toolkit
# Punkt Sentence Tokenizer https://www.nltk.org/api/nltk.tokenize.html#module-nltk.tokenize.punkt
import nltk
nltk.download('punkt')

df['lyrics'] = df['lyrics'].apply(nltk.word_tokenize)
df.head()

[nltk_data] Downloading package punkt to /home/cegard/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

  label                                             lyrics
0     0                             [fuck, all, you, hoes]
1     0                       [get, a, grip, motherfucker]
2     0  [yeah, this, album, is, dedicated, to, all, th...
3     0  [id, never, amount, to, nothin, to, all, the, ...
4     0  [buildings, that, i, was, hustlin, in, front, ...

In [32]:
# https://www.nltk.org/api/nltk.stem.html
#https://tartarus.org/martin/PorterStemmer/
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()
df['lyrics'] = df['lyrics'].apply(lambda x: [stemmer.stem(y) for y in x]) 
df.head()

  label                                             lyrics
0     0                              [fuck, all, you, hoe]
1     0                         [get, a, grip, motherfuck]
2     0  [yeah, thi, album, is, dedic, to, all, the, te...
3     0  [id, never, amount, to, nothin, to, all, the, ...
4     0  [build, that, i, wa, hustlin, in, front, of, t...

In [33]:
# Converts the list of words into space-separated strings
df['lyrics'] = df['lyrics'].apply(lambda x: ' '.join(x))
df.head()

  label                                             lyrics
0     0                                   fuck all you hoe
1     0                              get a grip motherfuck
2     0  yeah thi album is dedic to all the teacher tha...
3     0  id never amount to nothin to all the peopl tha...
4     0  build that i wa hustlin in front of that call ...

In [34]:
# Convert a collection of text documents to a matrix of token counts
# http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html
# http://scikit-learn.org/stable/modules/feature_extraction.html#text-feature-extraction
# to allow one letter words count_vect = CountVectorizer(token_pattern = r"(?u)\b\w+\b")
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer(token_pattern = r"(?u)\b\w+\b")
counts = count_vect.fit_transform(df['lyrics'])  
print counts

  (0, 1037)	1
  (0, 2515)	1
  (0, 63)	1
  (0, 858)	1
  (1, 1443)	1
  (1, 942)	1
  (1, 19)	1
  (1, 887)	1
  (2, 1369)	1
  (2, 2275)	1
  (2, 2215)	1
  (2, 2190)	1
  (2, 2217)	1
  (2, 2269)	1
  (2, 569)	1
  (2, 1142)	1
  (2, 58)	1
  (2, 2229)	1
  (2, 2507)	1
  (2, 63)	1
  (3, 24)	1
  (3, 1281)	1
  (3, 1607)	1
  (3, 1513)	1
  (3, 80)	1
  :	:
  (1967, 1907)	1
  (1967, 1211)	1
  (1967, 2116)	1
  (1967, 1251)	1
  (1967, 1529)	1
  (1967, 1369)	1
  (1967, 2217)	1
  (1968, 97)	1
  (1968, 149)	1
  (1968, 1846)	1
  (1968, 1525)	1
  (1968, 855)	1
  (1968, 641)	1
  (1968, 124)	1
  (1968, 83)	1
  (1968, 2217)	1
  (1968, 2269)	1
  (1969, 328)	1
  (1969, 2219)	1
  (1969, 1325)	1
  (1969, 2442)	1
  (1969, 1716)	1
  (1969, 2225)	1
  (1969, 641)	1
  (1969, 1142)	1

In [4]:
counts.shape

(5572, 9579)

In [ ]:
#from sklearn.feature_extraction.text import TfidfTransformer

#transformer = TfidfTransformer().fit(counts)

#counts = transformer.transform(counts)
#print counts

In [35]:
# https://stackoverflow.com/questions/28064634/random-state-pseudo-random-numberin-scikit-learn
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(counts, df['label'], test_size=0.1, random_state=69) 

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB().fit(X_train, y_train)  

import numpy as np
predicted = model.predict(X_test)
print(np.mean(predicted == y_test))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predicted))

0.766497461928934
[[63 32]
 [14 88]]

In [36]:
per = 0
for i in range(0,10):
    X_train, X_test, y_train, y_test = train_test_split(counts, df['label'], test_size=0.1) 
    model = MultinomialNB().fit(X_train, y_train)  

    import numpy as np
    predicted = model.predict(X_test)
    print(np.mean(predicted == y_test))
    per += np.mean(predicted == y_test)

    from sklearn.metrics import confusion_matrix
    print(confusion_matrix(y_test, predicted))

print "average perfromance"
print per/10.0

0.6598984771573604
[[48 44]
 [23 82]]
0.7157360406091371
[[59 37]
 [19 82]]
0.7868020304568528
[[60 25]
 [17 95]]
0.7309644670050761
[[ 44  25]
 [ 28 100]]
0.7208121827411168
[[62 39]
 [16 80]]
0.7563451776649747
[[60 30]
 [18 89]]
0.7106598984771574
[[47 29]
 [28 93]]
0.6903553299492385
[[51 41]
 [20 85]]
0.7563451776649747
[[53 29]
 [19 96]]
0.7208121827411168
[[52 37]
 [18 90]]
average perfromance
0.7248730964467006

In [37]:
per = 0
for i in range(0,10):
    X_train, X_test, y_train, y_test = train_test_split(counts, df['label'], test_size=0.2) 
    model = MultinomialNB().fit(X_train, y_train)  

    import numpy as np
    predicted = model.predict(X_test)
    print(np.mean(predicted == y_test))
    per += np.mean(predicted == y_test)

    from sklearn.metrics import confusion_matrix
    print(confusion_matrix(y_test, predicted))

print "average perfromance"
print per/10.0

0.7461928934010152
[[107  66]
 [ 34 187]]
0.7385786802030457
[[102  78]
 [ 25 189]]
0.7461928934010152
[[107  65]
 [ 35 187]]
0.7411167512690355
[[ 94  68]
 [ 34 198]]
0.7258883248730964
[[ 97  71]
 [ 37 189]]
0.7309644670050761
[[110  73]
 [ 33 178]]
0.6979695431472082
[[110  84]
 [ 35 165]]
0.7131979695431472
[[109  77]
 [ 36 172]]
0.7385786802030457
[[105  71]
 [ 32 186]]
0.7055837563451777
[[ 96  76]
 [ 40 182]]
average perfromance
0.7284263959390862

In [38]:
per = 0
for i in range(0,10):
    X_train, X_test, y_train, y_test = train_test_split(counts, df['label'], test_size=0.5) 
    model = MultinomialNB().fit(X_train, y_train)  

    import numpy as np
    predicted = model.predict(X_test)
    print(np.mean(predicted == y_test))
    per += np.mean(predicted == y_test)

    from sklearn.metrics import confusion_matrix
    print(confusion_matrix(y_test, predicted))

print "average perfromance"
print per/10.0

0.7126903553299493
[[235 221]
 [ 62 467]]
0.7035532994923858
[[210 231]
 [ 61 483]]
0.7086294416243655
[[237 198]
 [ 89 461]]
0.7370558375634517
[[246 182]
 [ 77 480]]
0.7208121827411168
[[236 188]
 [ 87 474]]
0.698477157360406
[[227 216]
 [ 81 461]]
0.6923857868020304
[[217 220]
 [ 83 465]]
0.7025380710659899
[[213 226]
 [ 67 479]]
0.7076142131979696
[[223 207]
 [ 81 474]]
0.7279187817258883
[[236 191]
 [ 77 481]]
average perfromance
0.7111675126903554